# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbox',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
