# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('command', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CommandSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='commandset',
            name='operating_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.OperatingSystem'),
        ),
        migrations.AddField(
            model_name='command',
            name='command_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.CommandSet'),
        ),
    ]
