# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 18:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu_limit',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='server',
            name='disk_limit',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='server',
            name='is_for_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='ram_limit',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='server',
            name='static_mailbox_quota',
            field=models.IntegerField(default=0),
        ),
    ]
