# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
