# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20170417_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cpu_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='server',
            name='disk_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='ram_size',
            field=models.IntegerField(default=0),
        ),
    ]
